# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
    - name: Deploy
      uses: zivan/action@master
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        # known-hosts: ${{ secrets.KNOWN_HOSTS }}
        # ssh-config: ${{ secrets.CONFIG }}
        dep: deploy -vvv
